export const RESPONSE_MESSAGE = {
    SUCCESS: 'Success',
    CARD_DETAILS_CREATED_SUCCESSFULLY: 'Card details created successfully',
    INVALIDEMAILORPASSWORD: 'Invalid email or password',
    NO_LOGIN_ACCOUNT: 'No login account',
    CARD_NOT_FOUND: 'Card not found',
    FILE_NOT_FOUND: 'File not found',
    CARD_UPDATED_SUCCESSFULLY: 'Card updated successfully',
    CARD_DELETED_SUCCESSFULLY: 'Card deleted successfully',
    CARD_ID_REQUIRED: 'Card is not valid or not found',
    CARD_DETAILS_RETRIEVED_SUCCESSFULLY: 'Card details retrieved successfully',
    YOU_HAVE_SUBSCRIBED_SUCCESSFULLY: "You have subscribed successfully",
    THIS_EMAIL_IS_ALREADY_SUBSCRIBED: "This email is already subscribed",
    THIS_REQUEST_IS_ALREADY_EXIST: "This request is already exist",
    REQUEST_SENT_SUCCESSFULLY: "Request sent successfully",
    COMPANY_DETAILS_CREATED_SUCCESSFULLY: 'Company details created successfully',
    COMPANY_ID_REQUIRED: 'Company is not valid or not found',
    COMPANY_NOT_FOUND: 'Company not found',
    COMPANY_UPDATED: 'Company details has been updated',
    COMPANY_DELETED_SUCCESSFULLY: 'Company deleted successfully',
};
